Issue 25 - addres alanı eklendi ve tum kullanıcıları alan API yeniden duzenlendi.
tahafurkanunsal/SpringBoot-MySQL-Project-2 pull request #30
Opened 2022-10-23 10:15 UTC by tahafurkanunsal

2022-10-23 14:36 UTC, azizunsal requested changes
Gelistirme OK gibi.
Fakat soyle durumlar var; 

- `address` alanini `getAll` ile client'a gondermiyorsak, `get` ile de gondermemek gerekir.
- Client'a bu alani gondermiyorsak, o zaman guncellenmesini de istemiyoruzdur. Dolayisiyla `update` isleminde bu alan guncellenmemeli.

Bu arada `address` alanini degil `username` alanini client'tan saklayalim.

2022-10-23 14:44 UTC, tahafurkanunsal commented
>

2022-10-23 14:46 UTC, azizunsal commented
Neden kapattin?

2022-10-23 14:46 UTC, tahafurkanunsal commented
bişey yazıcaktım sonra vazgeçtim commenti kapattım.

2022-10-23 15:25 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/usermanagement/service/UserService.java
> +        return null;
Daha once `null` donmuyordun, bu sekle cevirmenin sebebi nedir?

2022-10-23 15:28 UTC, tahafurkanunsal commented
örnekleri inceleyerek yapıyorum null kısmını bende anlamadım ancak orayı
hangi şekilde yapmam gerektiğini bulamadığım için null döndüm.

Aziz Unsal ***@***.***>, 23 Eki 2022 Paz, 18:26 tarihinde
şunu yazdı:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/main/java/tahafurkan/sandbox/usermanagement/service/UserService.java
> <https://github.com/tahafurkanunsal/SpringBoot-MySQL-Project-2/pull/30#discussion_r1002727550>
> :
>
> > -        existingUser.setEmail(user.getEmail());
> -        String username = user.getUsername();
> -        checkUsername(username);
> -        existingUser.setUsername(username);
> -        return userRepository.save(existingUser);
> +        Optional<User> existingUser = userRepository.findById(id);
> +        if (existingUser.isPresent()) {
> +            existingUser.get().setName(user.getName());
> +            existingUser.get().setLastName(user.getLastName());
> +            existingUser.get().setEmail(user.getEmail());
> +            existingUser.get().setAddress((user.getAddress()));
> +            String username = user.getUsername();
> +            checkUsername(username);
> +            return userRepository.save(existingUser.get());
> +        }
> +        return null;
>
> Daha once null donmuyordun, bu sekle cevirmenin sebebi nedir?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tahafurkanunsal/SpringBoot-MySQL-Project-2/pull/30#pullrequestreview-1152325596>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZUV5P5AEVOCKICDQ2ADZR3WEVKIRANCNFSM6AAAAAARMHIZTM>
> .
> You are receiving this because you modified the open/close state.Message
> ID: <tahafurkanunsal/SpringBoot-MySQL-Project-2/pull/30/review/1152325596@
> github.com>
>

2022-10-24 15:14 UTC, azizunsal approved these changes

2022-10-24 15:15 UTC, azizunsal commented
Mege edebilirsin, bundan sonra issue #26 ile devam et.

2022-10-24 15:17 UTC, merged