Issue 34
tahafurkanunsal/SpringBoot-MySQL-Project-2 pull request #36
Opened 2022-11-03 07:58 UTC by tahafurkanunsal

2022-11-03 13:00 UTC, azizunsal reviewed
checkUsername metodu icin test(ler) yazman gerekiyor oncelikle.

2022-11-06 13:03 UTC, azizunsal commented on src/test/java/tahafurkan/sandbox/usermanagement/service/UserServiceTest.java
> +
Farkli test metotlari olarak yazdigin,
`shouldCheckIfUsernameExists` ve 
`shouldCheckTheAvailabilityOfTheUsername` metotlari tam olarak neyi test ediyorlar?

Icerikleri birebir ayni olan 2 metot neden var?

2022-11-06 13:05 UTC, azizunsal requested changes
Test metotlarinin tekrar yazilmasi gerekiyor.

2022-11-06 13:08 UTC, tahafurkanunsal commented on src/test/java/tahafurkan/sandbox/usermanagement/service/UserServiceTest.java
> +
ya nasıl söylesem araştırıyorum ancak bulamıyorum bazı yerlere sorunumu söylediğimde kimse private metod testi daha önce yapmamış ve neden yaptıgımı soruguluyorlar . bu metodları yazarkende zorlandım acıkcası

2022-11-06 15:36 UTC, azizunsal commented on src/test/java/tahafurkan/sandbox/usermanagement/service/UserServiceTest.java
> +
Private metotlarin testi yapilmali mi yapilmamali mi konusu tartisma kabul eder bir konu olabilir evet. Buna ragmen bazi durumlarda private metotlarin testi yapilabilir.

```java
Method method = UserService.class.getDeclaredMethod("checkUsername", String.class);
method.setAccessible(true);
```
Bu kod private metodu test edebilmeni sagliyor, yapabime konusu ok yani.

Burada `checkUsername` metodu sadece `create` metodu tarafindan kullaniliyor. `create` metodunu tum durumlariyla test edersen `checkUsername` metoduna test yazman gerekmeyeBILIR. Onemli olan `unit test`'leri NICIN yazdigini anlaman.

Bunlar bir kenara sordugum sorularin cevabi bunlar degil, sen ismi farkli olan fakat icerigi ayni olan 2 metot yazmissin ve bunlarin farkli durumlari test edecegini dusunmussun/varsaymissin. YANLIS.

`create` metodunun testi de dogru degil.

2022-12-01 17:38 UTC, tahafurkanunsal commented
yapmış oldugum unit test işlemi doğru mu?

2022-12-03 11:51 UTC, azizunsal requested changes
**Unit test(=birim test) demek, en kucuk birimi(yani burada buna metot diyebiliriz) blogunu test etmek anlaminda kullaniliyor.**
UserService'deki tum metotlar birer unit.
Bu issue ile `UserService`'deki `checkUsername` metodunun birim testlerini yazmani istedim. Bu metoda ekledigimiz `dummy` username check de sadece senin unit testleri yazman icin bir sebep yaratmakti.
Diper repository'ye giden metotlarin bagimliliklari oldugu icin testlerini yazmak daha karmasik, mock objeler vs kullanmak gerekebilir yerine gore.

Donelim ` checkUsername` metoduna, ne yapiyor bu metot?
1. Kendisine bir string oalrak gelen parametreyi kontrol ediyor ve `dummy`'ye esit mi diye bakiyor. 
2. Eger gelen parametre `dummy` ise bir exception firlatiyor.
3. Degilse, bu sefer parametre olarak gelen username daha once kullanilmis mi(database'de mevcut mu) diye bakiyor
4. Mevcut ise baska bir exception firlatiyor.
5. Degilse hicbir sey yapmadan calismasini bitiriyor.

**Bu metot icin testler yazilacaksa(unit=birim=`checkUsername` metodu) yukaridaki maddeler kontrol edilmeli degil mi, yani:**
1. Bir test  `dummy` username gonderir ve metot exc firlatiyor mu diye kontrol eder.
2. Baska bir test `dummy` olmayan ama db'de bulunan(burada mocklar kullanilmali ki repository metodu db'de bir kayit varmis gibi davransin), bir username gonderir ve ilgili exc. firlatiliyor mu diye kontrol eder.
3. Baska bir unit test `dummy`'ye esit olmayan ve de db'de olmayan bir username gonderir ve test metodu, gercek metodun bu durumda hicbir exception firlatmadigini kontrol eder (bunu nasil yaparsin; test metodunda gerek metodun bir alt satirine gecebiliyorsan, exc gelmemistir ve test okdir.) Bu case de bir optional olarak bir kontrol daha yapilabilir (eger yapabilirsen, daha zor), kodun mockladigin repo. metoduna girip girmedigini kontrol edersin.

Netice olarak buradaki kodlar yukaridakileri karsilamiyor. 
`create` icin olan testi simdilik sil. Yukarida detaylica anlattigim metot icin testleri yaz.

2022-12-03 11:56 UTC, closed without merging